import NewAccountCreator from '@/components/NewAccountCreator';
import { cn } from '@/lib/utils';
import { db } from '@/modules/db';
import type { Metadata } from 'next';
import { Poor_Story } from 'next/font/google';
import Link from 'next/link';
import './globals.scss';

// const inter = Inter({ subsets: ['latin'] });
const poor = Poor_Story({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accounts = await db.account.findMany({
    orderBy: { name: 'asc' },
    select: { id: true, name: true },
  });

  return (
    <html lang='en'>
      <body
        suppressHydrationWarning
        className={cn('min-h-screen bg-background font-sans antialiased flex', poor.variable)}
      >
        <div className='bg-slate-800 text-slate-100 w-[240px] flex flex-col p-2 gap-2'>
          {accounts.map(account => (
            <Link
              className='text-start hover:bg-slate-700 p-2'
              key={account.id}
              href={`/accounts/${account.id}`}
            >
              {account.name.toUpperCase() + ' ' + account.id.slice(0, 10) + '...'}
            </Link>
          ))}
          <NewAccountCreator />
        </div>
        <div className='p-4 w-full'>{children}</div>
      </body>
    </html>
  );
}
