import NewAccountCreator from '@/components/NewAccountCreator';
import { cn } from '@/lib/utils';
import { db } from '@/modules/db';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import Link from 'next/link';
import './globals.scss';

// const inter = Inter({ subsets: ['latin'] });
export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accounts = await db.account.findMany({
    orderBy: { name: 'asc' },
    select: { id: true, name: true },
  });
  return (
    <html lang='en'>
      <body
        suppressHydrationWarning
        className={cn('min-h-screen bg-background font-sans antialiased flex', fontSans.variable)}
      >
        <div className='bg-slate-800 text-slate-100 w-[240px] flex flex-col p-2'>
          {accounts.map(account => (
            <Link key={account.id} href={`/accounts/${account.id}`}>
              {account.name}
            </Link>
          ))}
          <NewAccountCreator />
        </div>
        {children}
      </body>
    </html>
  );
}
